function C_mat = C_matrix(l1,l2,in3)
%C_matrix
%    C_mat = C_matrix(L1,L2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Mar-2025 16:02:20

q1 = in3(1,:);
q2 = in3(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l2.*t3;
t6 = l2.*t4;
t7 = -t6;
C_mat = reshape([t7-l1.*sin(q1),t5+l1.*cos(q1),t7,t5,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
end
