function A_matrix = A_matrix(in1,in2)
%A_matrix
%    A_matrix = A_matrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2025 14:37:19

theta2 = in1(2,:);
theta1_dot = in1(3,:);
theta2_dot = in1(4,:);
u1 = in2(1,:);
u2 = in2(2,:);
t2 = cos(theta2);
t3 = sin(theta2);
t4 = theta1_dot.^2;
t5 = theta2_dot.^2;
t6 = t2.^2;
t7 = t3.^2;
t8 = t3.*theta1_dot.*2.24e+2;
t9 = t3.*theta2_dot.*2.24e+2;
t11 = t3.*theta2_dot.*7.168e+3;
t12 = t2.*t3.*theta2_dot.*7.68e+3;
t10 = t6.*1.44e+2;
t13 = t10-5.81e+2;
t14 = 1.0./t13;
t15 = t14.^2;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,t14.*(t2.*t4.*1.12e+2+t2.*t5.*1.12e+2+t4.*t6.*1.2e+2-t4.*t7.*1.2e+2+t3.*u2.*7.5e+1+t2.*theta1_dot.*theta2_dot.*2.24e+2).*(-6.0./5.0)-t2.*t3.*t15.*(u1.*7.0e+1-u2.*7.0e+1+t3.*t4.*1.12e+2+t3.*t5.*1.12e+2+t8.*theta2_dot-t2.*u2.*7.5e+1+t2.*t3.*t4.*1.2e+2).*3.456e+2];
mt2 = [t14.*(t2.*t4.*2.0184e+4+t2.*t5.*3.584e+3+t4.*t6.*7.68e+3-t4.*t7.*7.68e+3+t5.*t6.*3.84e+3-t5.*t7.*3.84e+3-t3.*u1.*2.4e+3+t3.*u2.*4.8e+3+t2.*theta1_dot.*theta2_dot.*7.168e+3+t6.*theta1_dot.*theta2_dot.*7.68e+3-t7.*theta1_dot.*theta2_dot.*7.68e+3).*(3.0./8.0e+1)+t2.*t3.*t15.*(u1.*2.24e+3-u2.*1.2615e+4+t3.*t4.*2.0184e+4+t3.*t5.*3.584e+3+t11.*theta1_dot+t12.*theta1_dot+t2.*u1.*2.4e+3-t2.*u2.*4.8e+3+t2.*t3.*t4.*7.68e+3+t2.*t3.*t5.*3.84e+3).*(5.4e+1./5.0),1.0,0.0,t14.*(t8+t9+t2.*t3.*theta1_dot.*2.4e+2).*(-6.0./5.0)];
mt3 = [t14.*(t11+t12+t3.*theta1_dot.*4.0368e+4+t2.*t3.*theta1_dot.*1.536e+4).*(3.0./8.0e+1),0.0,1.0,t14.*(t8+t9).*(-6.0./5.0),t14.*(t11+t12+t3.*theta1_dot.*7.168e+3+t2.*t3.*theta1_dot.*7.68e+3).*(3.0./8.0e+1)];
A_matrix = reshape([mt1,mt2,mt3],4,4);
end
