function B_matrix = B_matrix(in1,in2)
%B_matrix
%    B_matrix = B_matrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2025 14:37:19

theta2 = in1(2,:);
t2 = cos(theta2);
t3 = t2.^2;
t4 = t3.*1.44e+2;
t5 = t4-5.81e+2;
t6 = 1.0./t5;
B_matrix = reshape([0.0,0.0,t6.*-8.4e+1,t6.*(t2.*2.4e+3+2.24e+3).*(3.0./8.0e+1),0.0,0.0,t6.*(t2.*7.5e+1+7.0e+1).*(6.0./5.0),t6.*(t2.*4.8e+3+1.2615e+4).*(-3.0./8.0e+1)],[4,2]);
end
