function P = PE(g,l1,lc1,l2,lc2,m1,m2,in8)
%PE
%    P = PE(G,L1,LC1,L2,LC2,M1,M2,IN8)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    19-Mar-2025 13:25:03

q1 = in8(1,:);
q2 = in8(2,:);
y0 = in8(4,:);
t2 = sin(q1);
P = g.*m1.*(y0+lc1.*t2)+g.*m2.*(y0+l1.*t2+lc2.*sin(q1+q2));
end
