function B_matrix = B_matrix(m)
%B_matrix
%    B_matrix = B_matrix(M)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    10-Mar-2025 22:32:27

t2 = 1.0./m;
t3 = t2.*2.0;
t4 = -t2;
B_matrix = reshape([0.0,0.0,0.0,0.0,0.0,t3,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,t3,0.0,0.0,0.0],[10,2]);
end
