function K = KE(l1,l2,l3,m1,m2,m3,q1,q2,q3,x0,y0,q1_d,q2_d,q3_d,x0_d,y0_d)
%KE
%    K = KE(L1,L2,L3,M1,M2,M3,Q1,Q2,Q3,X0,Y0,Q1_D,Q2_D,Q3_D,X0_D,Y0_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2025 21:50:56

t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = q1_d+q2_d;
t10 = -x0_d;
t6 = cos(t4);
t7 = q3+t4;
t8 = q3_d+t5;
t9 = sin(t4);
t11 = l1.*q1_d.*t2;
t12 = l1.*q1_d.*t3;
K = (m3.*((t11+y0_d+(l3.*t8.*cos(t7))./2.0+l2.*t5.*t6).^2+(t10+t12+(l3.*t8.*sin(t7))./2.0+l2.*t5.*t9).^2))./2.0+(m1.*((t11./2.0+y0_d).^2+(t12./2.0-x0_d).^2))./2.0+(m2.*((t10+t12+(l2.*t5.*t9)./2.0).^2+(t11+y0_d+(l2.*t5.*t6)./2.0).^2))./2.0+(l1.^2.*m1.*q1_d.^2)./2.4e+1+(l2.^2.*m2.*t5.^2)./2.4e+1+(l3.^2.*m3.*t8.^2)./2.4e+1;
end
