function P = PE(g,l1,l2,l3,m1,m2,m3,q1,q2,q3,x0,y0,q1_d,q2_d,q3_d,x0_d,y0_d)
%PE
%    P = PE(G,L1,L2,L3,M1,M2,M3,Q1,Q2,Q3,X0,Y0,Q1_D,Q2_D,Q3_D,X0_D,Y0_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Mar-2025 21:50:56

t2 = sin(q1);
t3 = q1+q2;
t4 = l1.*t2;
t5 = sin(t3);
t6 = (l2.*t5)./2.0;
P = g.*m2.*(t4+t6+y0+(l3.*sin(q3+t3))./2.0)+g.*m1.*(t4./2.0+y0)+g.*m2.*(t4+t6+y0);
end
